FROM golang:1.26.6 AS builder
ARG TARGETOS=linux
ARG TARGETARCH
WORKDIR /src
COPY examples/simple-worker/main.go ./main.go
RUN GOCACHE=/tmp/go-build CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -trimpath -ldflags="-s -w" -o /worker ./main.go && \
    rm -rf /tmp/go-build

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /worker /worker
USER 65532:65532
ENTRYPOINT ["/worker"]
