FROM golang:1.26.6 AS builder
ARG TARGETOS=linux
ARG TARGETARCH
WORKDIR /src
COPY test/fixture/runner/main.go ./main.go
RUN GOCACHE=/tmp/go-build CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -trimpath -ldflags="-s -w" -o /runner ./main.go && \
    rm -rf /tmp/go-build

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /runner /runner
USER 65532:65532
ENTRYPOINT ["/runner"]
